spec:
  template:
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: production
        resources:
          requests:
            cpu: "0.2"
#            memory: 256Mi
          limits:
            cpu: "1.0"
#            memory: 256Mi
